@extends('demo.layout.app')
@section('title', 'Activation Code')
@section('content')
    <!--begin::Content-->
    <div class="content d-flex flex-column flex-column-fluid" id="kt_content">
        <!--begin::Subheader-->
        <div class="subheader py-2 py-lg-6 subheader-solid" id="kt_subheader">
            <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
                <!--begin::Info-->
                <div class="d-flex align-items-center flex-wrap mr-1">
                    <!--begin::Page Heading-->
                    <div class="d-flex align-items-baseline flex-wrap mr-5"> 
                        <h5 class="text-dark font-weight-bold my-1 mr-5">Activation Code </h5> 
                        <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
                            <li class="breadcrumb-item">
                                <a href="{{ route('dashboard') }}" class="text-muted">Dashboard</a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="#" class="text-muted">Products</a>
                            </li> 
                            <li class="breadcrumb-item">
                                <a href="" class="text-muted">Activation Code</a>
                            </li>
                        </ul>
                    </div>
                </div> 
            </div>
        </div> 
        <div class="flex-column-fluid">
            <div class="container">
                <div class="card card-custom gutter-b"> 
                    <div class="card-header border-0 py-5 justify-content-right">
                        <h3 class="card-title "> 
                            <button type="button" 
                            data-toggle="modal" data-target="#generate-activation-code"
                            class="btn btn-danger btn-sm font-weight-bold rounded-0">Generate Activation Code</button>  
                        </h3> 
                    </div> 
                    <div class="card-body py-0"> 
                        <div class="table-responsive">
                            <table class="table table-head-custom table-vertical-center" id="kt_advance_table_widget_4">
                                <thead>
                                    <tr class="text-left">
                                        <th class="pl-0">S#</th>
                                        <th class="pl-0">Code</th>
                                        <th class="pl-0">Generated By</th> 
                                        <th class="pl-0">Spend PV</th> 
                                        <th  class="pl-0">Approval Flag </th>
                                        <th class="pl-0">Status</th> 
                                        <th class="pl-0">Used By</th> 
                                        <th class="pl-0">Used At</th>  
                                        <th class="pl-0">Created At </th> 
                                        <th class="pl-0">Action </th> 
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($activationCodes as $activationCode )
                                        <tr class="text-left"> 
                                            <td>{{ $loop->iteration }}</td>
                                            <th>{{ $activationCode->code }}</th>
                                            <td>{{ $activationCode->generatedBy->name }}</td>
                                            <td>{{ $activationCode->amount }}</td>
                                            <th>  {{ ucfirst ($activationCode->admin_approval)  }}</th> 
                                            <th>{{ ucfirst($activationCode->status)  }}</th>
                                            <td>{{ $activationCode->used_by ?? 'NA'  }}</td> 
                                            <td>{{ $activationCode->updated_at ?? 'NA' }}</td>
                                            <td>{{ $activationCode->created_at  }}</td> 
                                            <td>
                                                <button class="btn btn-sm btn-light-danger rounded-0 delete-btn" 
                                                    data-id="{{ $activationCode->id }}" 
                                                    data-toggle="modal" 
                                                    data-target="#delete-confirmation-modal">
                                                    <i class="icon-1x text-danger-50 flaticon-delete"></i>
                                                </button>
                                            </td> 
                                        </tr>
                                    @endforeach
                                </tbody> 
                            </table> 
                        </div>
                        <!--begin::Pagination-->
                        <div class="d-flex justify-content-between align-items-center flex-wrap">
                            <div class="d-flex flex-wrap py-2 mr-3">
                                
                            </div>
                        </div> 
                    </div> 
                </div> 
            </div> 
        </div> 
    </div> 

    <div class="modal fade" id="generate-activation-code" tabindex="-1" role="dialog"     aria-labelledby="exampleModalLabelDelete" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabelDelete">  Generate Activation Code </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <i aria-hidden="true" class="ki ki-close"></i>
                    </button>
                </div> 
                    <div class="modal-body"> 
                        <p>Your current PV balance: <strong id="currentPvBalance">{{ $totalBalance }}</strong></p>
                        <p>You need at least <strong class="text-danger">{{ $setting->activation_code }} PV</strong> to generate an activation code. The code can be shared with another user for registration.</p>
                        <p><strong>Click the button below to generate a new activation code.</strong></p>
                        <div id="codeResult" class="alert alert-success d-none"></div>
                    </div>
                    <div class="modal-footer">
                        <button id="generateCodeBtn" class="btn-sm btn btn-primary rounded-0">🛠️ Generate Code</button>
                        <button type="button" class="btn btn-light-primary btn-sm font-weight-bold rounded-0" data-dismiss="modal">Close</button>
                       
                    </div> 
            </div>
        </div>
    </div>  

    <div class="modal fade" id="delete-confirmation-modal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Confirm Deletion</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <i aria-hidden="true" class="ki ki-close"></i>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to delete this activation code?</p>
                    <input type="hidden" id="deleteActivationCodeId">
                </div>
                <div class="modal-footer">
                    <button id="confirmDeleteBtn" class="btn btn-danger btn-sm rounded-0">🗑️ Delete</button>
                    <button type="button" class="btn btn-light btn-sm font-weight-bold rounded-0" data-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </div>

    

@endsection
@section('page_js')
    <script>
        document.getElementById('generateCodeBtn').addEventListener('click', function () {
            fetch('/generate-code', {
                method: 'POST',
                headers: {
                    'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').content,
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({})
            })
            .then(response => response.json())
            .then(data => {
                if (data.data) {
                    toastr.success(`Your Activation Code: ${data.data.code}`);   
                    let newRow = `
                        <tr class="text-left"> 
                            <td>${data.data.id}</td>
                            <th>${data.data.code}</th>
                            <td>${data.data.generated_by.name}</td>
                            <td>${data.data.amount}</td>
                            <td>${data.data.admin_approval}</td>
                            <th>${data.data.status}</th>
                            <td>${data.data.used_by ?? 'N/A'}</td> 
                            <td>${data.data.updated_at ?? 'N/A'}</td>
                            <td>${data.data.created_at}</td>
                            <td>                   
                                <button class="btn btn-sm btn-light-danger rounded-0 delete-btn" 
                                    data-id="${data.data.id}" 
                                    data-toggle="modal" 
                                    data-target="#delete-confirmation-modal">
                                    <i class="icon-1x text-danger-50 flaticon-delete"></i>
                                </button>
                            </td>
                        </tr>
                    `;
                    document.querySelector('tbody').insertAdjacentHTML('afterbegin', newRow);
                    document.getElementById('currentPvBalance').innerText = data.new_balance;
                    $('#generate-activation-code').modal('hide');
                } 
            })
            .catch(error => console.error('Error:', error));
        });  
    </script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            let deleteCodeId = null; 
            // When the delete button is clicked, set the ID
            document.querySelectorAll('.delete-btn').forEach(button => {
                button.addEventListener('click', function () {
                    deleteCodeId = this.getAttribute('data-id');
                    document.getElementById('deleteActivationCodeId').value = deleteCodeId;
                });
            }); 
            document.getElementById('confirmDeleteBtn').addEventListener('click', function () {
                if (!deleteCodeId) return;
    
                fetch(`/delete-code/${deleteCodeId}`, {
                    method: 'DELETE',
                    headers: {
                        'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').content,
                        'Content-Type': 'application/json'
                    }
                })
                .then(response => response.json())
                .then(data => {
                    if (data.success) {
                        toastr.success('Activation code deleted successfully!');
                        document.querySelector(`button[data-id="${deleteCodeId}"]`).closest('tr').remove();
                        $('#delete-confirmation-modal').modal('hide');
                    } else {
                        toastr.error('Failed to delete activation code.');
                    }
                })
                .catch(error => console.error('Error:', error));
            });
        });
    </script>
    

@endsection
