<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Services\AccountManagementService;
use App\Services\AutomatedROIService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class ROISubmissionMonitoringController extends Controller
{
    private AccountManagementService $accountService;
    private AutomatedROIService $roiService;

    public function __construct(
        AccountManagementService $accountService,
        AutomatedROIService $roiService
    ) {
        $this->accountService = $accountService;
        $this->roiService = $roiService;
    }

    /**
     * Display ROI submission monitoring page
     */
    public function index(Request $request)
    {
        $dateFrom = $request->get('date_from', now()->toDateString());
        $dateTo = $request->get('date_to', now()->toDateString());
        $search = $request->get('search');

        // Get users who should have received ROI but didn't
        $query = User::where('roi_eligible_investment_amount', '>', 0)
            ->where('blocked', false)
            ->where('can_login', true)
            ->where('freez_wallet', false)
            ->where(function ($q) {
                $q->whereNull('roi_status')
                    ->orWhere('roi_status', 'active');
            });

        // Filter by last ROI payment date
        // Show users who either:
        // 1. Never received ROI (last_roi_payment_date is NULL)
        // 2. Last received ROI BEFORE the selected date range (not on or after dateTo)
        $query->where(function ($q) use ($dateTo) {
            $q->whereNull('last_roi_payment_date')
                ->orWhereDate('last_roi_payment_date', '<', $dateTo);
        });

        // Search filter
        if ($search) {
            $query->where(function ($q) use ($search) {
                $q->where('name', 'like', "%{$search}%")
                    ->orWhere('username', 'like', "%{$search}%")
                    ->orWhere('email', 'like', "%{$search}%")
                    ->orWhere('id', $search);
            });
        }

        $users = $query->with(['profile'])->paginate(20);

        // Process each user to add ROI stats
        $users->getCollection()->transform(function ($user) {
            $user->roi_stats = $this->accountService->getRoiAccountStats($user);
            return $user;
        }); 
        return view('roi-submission.index', compact('users', 'dateFrom', 'dateTo', 'search'));
    }

    /**
     * Manually generate ROI for a specific user and date
     */
    public function generateManualROI(Request $request, User $user)
    {
        $validated = $request->validate([
            'date' => 'required|date|before_or_equal:today',
        ]);

        try {
            // Check if user can receive ROI
            if (!$this->accountService->canReceiveRoi($user)) {
                return redirect()->back()->with('error', "User {$user->username} cannot receive ROI at this time. ROI Status: {$user->roi_status}");
            }

            // Check if user has reached 2X limit
            if ($this->accountService->hasReached2XLimit($user)) {
                return redirect()->back()->with('error', "User {$user->username} has already reached 2X limit.");
            }

            // Trigger ROI
            $result = $this->roiService->triggerAutomatedROI($user, 'manual_admin_trigger');

            if ($result['success']) {
                Log::info('Manual ROI generated by admin', [
                    'user_id' => $user->id,
                    'username' => $user->username,
                    'amount' => $result['amount'],
                    'admin_id' => auth()->id(),
                    'trigger_date' => $validated['date']
                ]);

                return redirect()->back()->with('success', "ROI of $" . number_format($result['amount'], 2) . " generated successfully for {$user->username}");
            } else {
                return redirect()->back()->with('error', "Failed to generate ROI: {$result['message']}");
            }
        } catch (\Exception $e) {
            Log::error('Manual ROI generation failed', [
                'user_id' => $user->id,
                'username' => $user->username,
                'admin_id' => auth()->id(),
                'error' => $e->getMessage()
            ]);

            return redirect()->back()->with('error', 'Failed to generate ROI: ' . $e->getMessage());
        }
    }

    /**
     * Bulk generate ROI for all eligible users for a specific date
     */
    public function bulkGenerateROI(Request $request)
    {
        $validated = $request->validate([
            'date' => 'required|date|before_or_equal:today',
            'user_ids' => 'nullable|array',
            'user_ids.*' => 'exists:users,id'
        ]);

        try {
            $userIds = $validated['user_ids'] ?? [];
            $date = $validated['date'];

            if (empty($userIds)) {
                // Get all eligible users
                $users = User::where('roi_eligible_investment_amount', '>', 0)
                    ->where('blocked', false)
                    ->where('can_login', true)
                    ->where('freez_wallet', false)
                    ->where(function ($q) {
                        $q->whereNull('roi_status')
                            ->orWhere('roi_status', 'active');
                    })
                    ->whereDate('last_roi_payment_date', '<', $date)
                    ->get();
            } else {
                $users = User::whereIn('id', $userIds)->get();
            }

            $processed = 0;
            $failed = 0;
            $totalAmount = 0;

            foreach ($users as $user) {
                if (!$this->accountService->canReceiveRoi($user)) {
                    $failed++;
                    continue;
                }

                $result = $this->roiService->triggerAutomatedROI($user, 'bulk_manual_admin_trigger');

                if ($result['success']) {
                    $processed++;
                    $totalAmount += $result['amount'];
                } else {
                    $failed++;
                }
            }

            Log::info('Bulk ROI generation completed', [
                'processed' => $processed,
                'failed' => $failed,
                'total_amount' => $totalAmount,
                'admin_id' => auth()->id(),
                'trigger_date' => $date
            ]);

            return redirect()->back()->with('success', "Bulk ROI generation completed: {$processed} users processed, {$failed} failed. Total amount: $" . number_format($totalAmount, 2));
        } catch (\Exception $e) {
            Log::error('Bulk ROI generation failed', [
                'admin_id' => auth()->id(),
                'error' => $e->getMessage()
            ]);

            return redirect()->back()->with('error', 'Bulk ROI generation failed: ' . $e->getMessage());
        }
    }
}