@extends('demo.layout.app')
@section('title', 'Saving Plan Instalment Commissions')

@section('content')
<div class="content d-flex flex-column flex-column-fluid" id="kt_content">

    {{-- Subheader --}}
    <div class="py-2 subheader py-lg-6 subheader-solid" id="kt_subheader">
        <div class="flex-wrap container-fluid d-flex align-items-center justify-content-between flex-sm-nowrap">
            <div class="flex-wrap mr-1 d-flex align-items-center">
                <div class="d-flex align-items-baseline">
                    <h5 class="my-1 mr-5 text-dark font-weight-bold">Saving Plan — Instalment Commissions</h5>
                    <ul class="p-0 my-2 breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold font-size-sm">
                        <li class="breadcrumb-item"><a href="{{ route('dashboard') }}" class="text-muted">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('admin.saving.index') }}" class="text-muted">Saving Accounts</a></li>
                        <li class="breadcrumb-item"><a href="#" class="text-muted">Instalment Commissions</a></li>
                    </ul>
                </div>
            </div>
            <div class="gap-2 d-flex">
                @if($totalPending > 0)
                    <button type="button" class="btn btn-sm btn-success" data-toggle="modal" data-target="#sendAllModal">
                        <i class="mr-1 fas fa-paper-plane"></i> Send All Pending ({{ $totalPending }})
                    </button>
                @endif
            </div>
        </div>
    </div>

    <div class="flex-column-fluid">
        <div class="container">

            {{-- Alerts --}}
            @foreach(['success','error','warning','info'] as $type)
                @if(session($type))
                    <div class="alert alert-{{ $type === 'error' ? 'danger' : $type }} alert-dismissible fade show mb-4">
                        {{ session($type) }}
                        <button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
                    </div>
                @endif
            @endforeach

            {{-- Summary Cards --}}
            <div class="mb-6 row">
                <div class="col-md-3">
                    <div class="text-white card card-custom bg-warning">
                        <div class="py-5 text-center card-body">
                            <div style="font-size:1.8rem; font-weight:700;">{{ $totalPending }}</div>
                            <div class="mt-1 font-size-sm">Pending Commissions</div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="text-white card card-custom bg-danger">
                        <div class="py-5 text-center card-body">
                            <div style="font-size:1.8rem; font-weight:700;">${{ number_format($pendingAmount, 2) }}</div>
                            <div class="mt-1 font-size-sm">Pending Amount</div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="text-white card card-custom bg-success">
                        <div class="py-5 text-center card-body">
                            <div style="font-size:1.8rem; font-weight:700;">{{ $totalPaid }}</div>
                            <div class="mt-1 font-size-sm">Paid Commissions</div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="text-white card card-custom bg-primary">
                        <div class="py-5 text-center card-body">
                            <div style="font-size:1.8rem; font-weight:700;">${{ number_format($paidAmount, 2) }}</div>
                            <div class="mt-1 font-size-sm">Total Paid Amount</div>
                        </div>
                    </div>
                </div>
            </div>

            {{-- Backfill notice --}}
            @if($totalPending > 0)
            <div class="mb-5 alert alert-warning">
                <strong>{{ $totalPending }} pending commission(s)</strong> found.
                These were generated by the backfill command and are awaiting admin approval.
                Review the records below and use <strong>Send All Pending</strong> or send individually.
            </div>
            @endif

            {{-- Filters --}}
            <div class="mb-5 card card-custom gutter-b">
                <div class="py-4 card-body">
                    <form method="GET" action="{{ route('admin.saving.instalment-commissions') }}" class="row align-items-end g-3">
                        <div class="col-md-2">
                            <label class="mb-1 font-size-sm font-weight-bold">Status</label>
                            <select name="status" class="form-control form-control-sm">
                                <option value="">All</option>
                                <option value="pending" @selected(request('status') === 'pending')>Pending</option>
                                <option value="paid"    @selected(request('status') === 'paid')>Paid</option>
                                <option value="skipped" @selected(request('status') === 'skipped')>Skipped</option>
                            </select>
                        </div>
                        <div class="col-md-2">
                            <label class="mb-1 font-size-sm font-weight-bold">Member</label>
                            <select name="user_id" class="form-control form-control-sm">
                                <option value="">All members</option>
                                @foreach($savingUsers as $u)
                                    <option value="{{ $u->id }}" @selected(request('user_id') == $u->id)>
                                        {{ $u->name }} (@ {{ $u->username }})
                                    </option>
                                @endforeach
                            </select>
                        </div>
                        <div class="col-md-2">
                            <label class="mb-1 font-size-sm font-weight-bold">Upline / Sponsor</label>
                            <select name="ancestor_id" class="form-control form-control-sm">
                                <option value="">All uplines</option>
                                @foreach($savingUsers as $u)
                                    <option value="{{ $u->id }}" @selected(request('ancestor_id') == $u->id)>
                                        {{ $u->name }} (@ {{ $u->username }})
                                    </option>
                                @endforeach
                            </select>
                        </div>
                        <div class="col-md-1">
                            <label class="mb-1 font-size-sm font-weight-bold">Inst #</label>
                            <input type="number" name="instalment_number" min="1" max="25"
                                   class="form-control form-control-sm"
                                   value="{{ request('instalment_number') }}" placeholder="1–25">
                        </div>
                        <div class="col-md-2">
                            <label class="mb-1 font-size-sm font-weight-bold">Confirmed From</label>
                            <input type="date" name="from" class="form-control form-control-sm" value="{{ request('from') }}">
                        </div>
                        <div class="col-md-2">
                            <label class="mb-1 font-size-sm font-weight-bold">Confirmed To</label>
                            <input type="date" name="to" class="form-control form-control-sm" value="{{ request('to') }}">
                        </div>
                        <div class="col-md-3">
                            <label class="mb-1 font-size-sm font-weight-bold">Search name / username</label>
                            <input type="text" name="search" class="form-control form-control-sm"
                                   value="{{ request('search') }}" placeholder="Search…">
                        </div>
                        <div class="gap-2 col-md-auto d-flex align-items-end" style="gap:.5rem;">
                            <button class="btn btn-sm btn-primary">Filter</button>
                            <a href="{{ route('admin.saving.instalment-commissions') }}" class="btn btn-sm btn-secondary">Reset</a>
                        </div>
                    </form>
                </div>
            </div>

            {{-- Table --}}
            <div class="card card-custom gutter-b">
                <div class="py-4 border-0 card-header d-flex align-items-center justify-content-between">
                    <h3 class="mb-0 card-title font-weight-bolder text-dark">Commission Records</h3>
                    <span class="text-muted font-size-sm">{{ $commissions->total() }} record(s)</span>
                </div>
                <div class="pt-0 card-body">
                    <div class="table-responsive">
                        <table class="table table-hover table-head-custom table-vertical-center font-size-sm">
                            <thead>
                                <tr>
                                    <th>Member</th>
                                    <th>Upline / Sponsor</th>
                                    <th class="text-center">Inst #</th>
                                    <th class="text-right">Inst Amount</th>
                                    <th>Confirmed On</th>
                                    <th>Txn Ref</th>
                                    <th class="text-center">Level</th>
                                    <th class="text-right">Rate</th>
                                    <th class="text-right">Commission</th>
                                    <th class="text-center">Status</th>
                                    <th>Processed</th>
                                    <th class="text-center">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($commissions as $commission)
                                <tr>
                                    <td>
                                        <div class="font-weight-bold text-dark-75">{{ $commission->user->name ?? '—' }}</div>
                                        <div class="text-muted small">@ {{ $commission->user->username ?? '' }}</div>
                                    </td>
                                    <td>
                                        <div class="font-weight-bold">{{ $commission->ancestor->name ?? '—' }}</div>
                                        <div class="text-muted small">@ {{ $commission->ancestor->username ?? '' }}</div>
                                    </td>
                                    <td class="text-center font-weight-bold">#{{ $commission->instalment_number }}</td>
                                    <td class="text-right">${{ number_format($commission->instalment->amount ?? 0, 2) }}</td>
                                    <td>
                                        @if($commission->instalment && $commission->instalment->confirmed_at)
                                            {{ $commission->instalment->confirmed_at->format('d M Y') }}
                                        @else
                                            <span class="text-muted">—</span>
                                        @endif
                                    </td>
                                    <td>
                                        <span class="text-muted small">
                                            {{ $commission->instalment->transaction_id ?? '—' }}
                                        </span>
                                    </td>
                                    <td class="text-center">
                                        <span class="badge badge-{{ $commission->level === 1 ? 'primary' : 'secondary' }}">
                                            L{{ $commission->level }}
                                        </span>
                                        <div class="text-muted small">{{ $commission->commission_type }}</div>
                                    </td>
                                    <td class="text-right">{{ $commission->percentage }}%</td>
                                    <td class="text-right font-weight-bold">
                                        @if($commission->excess_reversed)
                                            <span class="text-primary">${{ number_format($commission->commission_amount, 4) }}</span>
                                            <div style="margin-top:2px;">
                                                <span class="badge badge-warning" style="font-size:9px;padding:2px 5px;">
                                                    <i class="fas fa-check" style="font-size:8px;"></i> corrected
                                                </span>
                                            </div>
                                        @else
                                            <span class="text-success">${{ number_format($commission->commission_amount, 4) }}</span>
                                        @endif
                                    </td>
                                    <td class="text-center">
                                        @if($commission->status === 'paid')
                                            <span class="badge badge-success">Paid</span>
                                        @elseif($commission->status === 'pending')
                                            <span class="badge badge-warning text-dark">Pending</span>
                                        @else
                                            <span class="badge badge-secondary">{{ ucfirst($commission->status) }}</span>
                                        @endif
                                    </td>
                                    <td>
                                        @if($commission->processed_at)
                                            <div class="small">{{ $commission->processed_at->format('d M Y') }}</div>
                                            @if($commission->processedBy)
                                                <div class="text-muted small">by {{ $commission->processedBy->name }}</div>
                                            @else
                                                <div class="text-muted small">auto</div>
                                            @endif
                                        @else
                                            <span class="text-muted">—</span>
                                        @endif
                                    </td>
                                    <td class="text-center">
                                        @if($commission->status === 'pending')
                                            <form method="POST"
                                                  action="{{ route('admin.saving.commissions.send-single', $commission) }}"
                                                  onsubmit="return confirm('Send ${{ number_format($commission->commission_amount, 2) }} to {{ addslashes($commission->ancestor->name ?? '') }}?')">
                                                @csrf
                                                <button class="btn btn-xs btn-success">
                                                    <i class="fas fa-paper-plane"></i> Send
                                                </button>
                                            </form>
                                        @else
                                            <span class="text-muted font-size-xs">—</span>
                                        @endif
                                    </td>
                                </tr>
                                @empty
                                <tr>
                                    <td colspan="12" class="py-8 text-center text-muted">
                                        No commission records found for the selected filters.
                                    </td>
                                </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>

                    {{-- Pagination --}}
                    @if($commissions->hasPages())
                    <div class="mt-4 d-flex justify-content-center">
                        {{ $commissions->withQueryString()->links() }}
                    </div>
                    @endif
                </div>
            </div>

        </div>
    </div>
</div>

{{-- Send All Modal --}}
<div class="modal fade" id="sendAllModal" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Send All Pending Commissions</h5>
                <button type="button" class="close" data-dismiss="modal"><span>&times;</span></button>
            </div>
            <form method="POST" action="{{ route('admin.saving.commissions.send-all') }}">
                @csrf
                <div class="modal-body">
                    <p>You are about to send <strong>{{ $totalPending }}</strong> pending commission(s)
                       totalling <strong>${{ number_format($pendingAmount, 2) }}</strong>.</p>
                    <p class="text-muted">Wallet entries will be created for each upline. This cannot be undone.</p>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="mb-0 form-group">
                                <label class="font-size-sm">Confirmed From (optional)</label>
                                <input type="date" name="from" class="form-control form-control-sm">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-0 form-group">
                                <label class="font-size-sm">Confirmed To (optional)</label>
                                <input type="date" name="to" class="form-control form-control-sm">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-success">
                        <i class="mr-1 fas fa-paper-plane"></i> Send All Pending
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection
